/*******************************************************************************
 * Copyright (c) 2004, 2006 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.gymnast.generator.core.ast;

import org.eclipse.gymnast.runtime.core.ast.ASTNode;

/**
 *
 * @generated by Gymnast from gymnast.ast on Aug 15, 2004 2:28:15 PM
 */
public class CompUnit extends GymnastASTNode  {


	private HeaderSection _headerSection;
	private Grammar _grammar;

	public HeaderSection getHeaderSection() {
		return _headerSection;
	}
	public Grammar getGrammar() {
		return _grammar;
	}


	/**
	 * @return the number of children of this ASTNode
	 */
	public int getChildCount() {
		int count = 0;
		if (_headerSection != null) count++;
		if (_grammar != null) count++;

		return count;
	}

	/**
	 * @param index the index of a child ASTNode to get
	 * @return the child ASTNode at the given index
	 * @throws IndexOutOfBoundsException when the index is out of bounds
	 */
	public ASTNode getChild(int index) {
		int count = -1;
		if ((_headerSection != null) && (++count == index)) return _headerSection;
		if ((_grammar != null) && (++count == index)) return _grammar;

		throw new IndexOutOfBoundsException();
	}
	
	/**
	 * Construct a new CompUnit.
	 */
	public CompUnit(
		HeaderSection headerSection,
		Grammar grammar
	) {
		super();

		if (headerSection != null) {
			_headerSection = headerSection;
			if (_headerSection._parent != null) throw new RuntimeException();
			_headerSection._parent = this;
		}
		if (grammar != null) {
			_grammar = grammar;
			if (_grammar._parent != null) throw new RuntimeException();
			_grammar._parent = this;
		}

	}

	/**
	 * This method overrides the superclass <code>acceptImpl</code> providing
	 * the same implementation.  Here <code>this</code> refers to this specific node
	 * class, so the <code>beginVisit</code> and <code>endVisit</code> methods
	 * specific to this type in the visitor will be invoked.
	 */
	public void acceptImpl(GymnastASTNodeVisitor visitor) {
		boolean visitChildren = visitor.beginVisit(this);
		if (visitChildren) visitChildren(visitor);
		visitor.endVisit(this);
	}

}
